---
global:
  prometheus_url: http://192.168.31.31:30104
  wechat_api_secret: <secret>
  wechat_api_corp_id: <secret>
  dingtalk_api_token: <secret>
  dingtalk_api_secret: <secret>

s3:
  access_key: <secret>
  secret_key: <secret>
  endpoint: oss-cn-beijing.aliyuncs.com
  region: cn-beijing
  bucket: <bucket>

receivers:
  - name: rcv1
    wechat_config:
      agent_id: <agent_id>
      to_user: "@all"
      message_type: markdown
      message: '{{ template "wechat.default.message" . }}'
    dingtalk_config:
      message_type: markdown
      markdown:
        title: '{{ template "dingtalk.default.title" . }}'
        text: '{{ template "dingtalk.default.content" . }}'
        at:
          atMobiles: [ "123456" ]
          isAtAll: false
