debug: true
http_port: 8080
timeout: 5s
prometheus_url: <prometheus_url>
metric_resolution: 100

s3:
  access_key: <ak>
  secret_key: <sk>
  endpoint: oss-cn-beijing.aliyuncs.com
  region: cn-beijing
  bucket: <bucket>

dingtalk:
  url: https://oapi.dingtalk.com/robot/send?access_token=<token>
  # secret for signature
  secret: <SEC>

