---
version: 2.1
orbs:
  prometheus: prometheus/prometheus@0.16.0
  go: circleci/go@1.7.1

executors:
  golang:
    # Whenever the Go version is updated here, .promu.yml should also be updated.
    docker:
      - image: quay.io/prometheus/golang-builder:1.17-base

jobs:
  test:
    executor: golang
    steps:
      - prometheus/setup_environment
      - go/load-cache:
          key: v1-go-mod
      - run:
          command: make
          environment:
            # By default Go uses GOMAXPROCS but a Circle CI executor has many
            # cores (> 30) while the CPU and RAM resources are throttled. If we
            # don't limit this to the number of allocated cores, the job is
            # likely to get OOMed and killed.
            GOOPTS: "-p 2"
            GOMAXPROCS: "2"
            GO111MODULE: "on"
      - prometheus/store_artifact:
          file: promoter
      - go/save-cache:
          key: v1-go-mod

workflows:
  version: 2
  promoter:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - prometheus/build:
          name: build
          parallelism: 3
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      - prometheus/publish_main:
          context: cnych-context
          requires:
            - test
            - build
          filters:
            branches:
              only: main
          docker_hub_organization: cnych
      - prometheus/publish_release:
          context: cnych-context
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
            branches:
              ignore: /.*/
          docker_hub_organization: cnych
