---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promoter-conf
  namespace: kube-mon
data:
  config.yaml: |
    global:
      prometheus_url: http://<prometheus_url>
      wechat_api_secret: <secret>
      wechat_api_corp_id: <secret>
      dingtalk_api_token: <secret>
      dingtalk_api_secret: <secret>

    s3:
      access_key: <secret>
      secret_key: <secret>
      endpoint: oss-cn-beijing.aliyuncs.com
      region: cn-beijing
      bucket: <bucket>

    receivers:
      - name: rcv1
        wechat_configs:
          - agent_id: <agent_id>
            to_user: "@all"
            message_type: markdown
            message: '{{ template "wechat.default.message" . }}'
        dingtalk_configs:
          - message_type: markdown
            at:
              atMobiles: [ "123456" ]
              isAtAll: false
            markdown:
              title: '{{ template "dingtalk.default.title" . }}'
              text: '{{ template "dingtalk.default.content" . }}'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promoter
  namespace: kube-mon
  labels:
    app: promoter
spec:
  selector:
    matchLabels:
      app: promoter
  template:
    metadata:
      labels:
        app: promoter
    spec:
      volumes:
        - name: config
          configMap:
            name: promoter-conf
        - name: timezone
          hostPath:
            path: /etc/localtime
      containers:
        - name: promoter
          image: cnych/promoter:main
          imagePullPolicy: IfNotPresent
          args:
            - "--config.file=/etc/promoter/config.yaml"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/etc/promoter"
              name: config
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: promoter
  namespace: kube-mon
  labels:
    app: promoter
spec:
  selector:
    app: promoter
  ports:
    - port: 8080
